# Generated by Django 2.2.3 on 2019-07-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kinds', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('kakaoTalkID', models.CharField(max_length=20)),
                ('expirationDate', models.CharField(max_length=20)),
            ],
        ),
    ]
